import mongoose from 'mongoose';

// Generate valid MongoDB ObjectIDs for schemes
const schemeIds = {
  scheme1: new mongoose.Types.ObjectId().toString(),
  scheme2: new mongoose.Types.ObjectId().toString(),
  scheme3: new mongoose.Types.ObjectId().toString(),
  scheme4: new mongoose.Types.ObjectId().toString(),
  scheme5: new mongoose.Types.ObjectId().toString(),
  scheme6: new mongoose.Types.ObjectId().toString(),
  scheme7: new mongoose.Types.ObjectId().toString(),
  scheme8: new mongoose.Types.ObjectId().toString(),
  scheme9: new mongoose.Types.ObjectId().toString(),
  scheme10: new mongoose.Types.ObjectId().toString(),
  scheme11: new mongoose.Types.ObjectId().toString(),
  scheme12: new mongoose.Types.ObjectId().toString(),
  scheme13: new mongoose.Types.ObjectId().toString(),
  scheme14: new mongoose.Types.ObjectId().toString(),
  scheme15: new mongoose.Types.ObjectId().toString(),
};

export const schemes = [
  {
    id: schemeIds.scheme1,
    title: "PM Kisan Samman Nidhi Yojana",
    description: "Financial assistance to farmer families across the country",
    category: "Agriculture",
    eligibility: "All landholding farmer families with cultivable land",
    benefits: "₹6,000 per year in three equal installments",
    application_process: "Apply online through the official PM-KISAN portal or visit your nearest Common Service Centre",
    documents: ["Aadhaar Card", "Land Records", "Bank Account Details"],
    deadline: "Ongoing scheme with quarterly payments",
    website: "https://pmkisan.gov.in/RegistrationFormNew.aspx",
    created_at: new Date().toISOString(),
  },
  {
    id: schemeIds.scheme2,
    title: "Pradhan Mantri Awas Yojana",
    description: "Housing for all by 2022 through financial assistance for house construction",
    category: "Housing",
    eligibility: "Households with annual income up to ₹18 lakhs, women, SC/ST, and other vulnerable groups",
    benefits: "Under PMAY-Urban, beneficiaries can receive an interest subsidy of up to ₹2.67 lakhs. Under PMAY-Gramin, financial assistance of ₹1.20 lakhs in plain areas and ₹1.30 lakhs in hilly/difficult areas is provided.",
    application_process: "Apply through the official PMAY portal or visit your local municipal office",
    documents: ["Aadhaar Card", "Income Certificate", "Property Documents", "Bank Account Details"],
    deadline: "Ongoing",
    website: "https://pmaymis.gov.in/PMAYMIS2_2024/Auth/Login.aspx",
    created_at: new Date().toISOString(),
  },
  {
    id: schemeIds.scheme3,
    title: "Ayushman Bharat Pradhan Mantri Jan Arogya Yojana",
    description: "Health insurance scheme providing coverage up to ₹5 lakhs per family per year",
    category: "Health",
    eligibility: "Poor and vulnerable families as per SECC data",
    benefits: "Free healthcare services, including hospitalization, medicines, and diagnostics up to ₹5 lakhs per family per year",
    application_process: "Check eligibility on the official website or visit your nearest Ayushman Bharat Kendra",
    documents: ["Aadhaar Card", "Ration Card", "SECC Database Details"],
    deadline: "Ongoing",
    website: "https://beneficiary.nha.gov.in/",
    created_at: new Date().toISOString(),
  },
  {
    id: schemeIds.scheme4,
    title: "Pradhan Mantri Ujjwala Yojana",
    description: "Providing LPG connections to women from BPL households",
    category: "Energy",
    eligibility: "Women from BPL households without LPG connection",
    benefits: "Free LPG connection with financial assistance for first refill and stove",
    application_process: "Apply through your nearest LPG distributor or Common Service Centre",
    documents: ["Aadhaar Card", "BPL Certificate", "Bank Account Details"],
    deadline: "Ongoing",
    website: "https://pmuy.gov.in/ujjwala2.html",
    created_at: new Date().toISOString(),
  },
  {
    id: schemeIds.scheme5,
    title: "Pradhan Mantri Mudra Yojana",
    description: "Providing loans up to ₹10 lakhs to non-corporate, non-farm small/micro enterprises",
    category: "Finance",
    eligibility: "Small businesses, entrepreneurs, and self-employed individuals",
    benefits: "Loans up to ₹10 lakhs categorized as Shishu (up to ₹50,000), Kishore (₹50,000 to ₹5 lakhs), and Tarun (₹5 lakhs to ₹10 lakhs)",
    application_process: "Apply through any commercial bank, RRB, small finance bank, or NBFC",
    documents: ["Identity Proof", "Address Proof", "Business Plan", "Bank Account Details"],
    deadline: "Ongoing",
    website: "https://pmmydata.mudra.org.in/##",
    created_at: new Date().toISOString(),
  },
  {
    id: schemeIds.scheme6,
    title: "National Education Policy Scholarships",
    description: "Scholarships for students at all levels to promote education and reduce dropout rates",
    category: "Education",
    eligibility: "Students aged 6-18 years from low-income families with annual income below ₹2.5 lakhs",
    benefits: "Financial assistance ranging from ₹5,000 to ₹50,000 per year based on education level and performance",
    application_process: "Apply through the National Scholarship Portal or your educational institution",
    documents: ["Aadhaar Card", "Income Certificate", "School/College Enrollment Certificate", "Bank Account Details"],
    deadline: "Applications open annually from June to September",
    website: "https://scholarships.gov.in/",
    created_at: new Date().toISOString(),
  },
  {
    id: schemeIds.scheme7,
    title: "PM Garib Kalyan Ann Yojana",
    description: "Food security program providing free foodgrains to poor families",
    category: "Welfare",
    eligibility: "All beneficiaries covered under the National Food Security Act (NFSA)",
    benefits: "5 kg of free foodgrains per person per month in addition to regular NFSA entitlements",
    application_process: "No separate application needed. Available through existing ration card at Fair Price Shops",
    documents: ["Ration Card", "Aadhaar Card"],
    deadline: "Extended periodically based on government decisions",
    website: "https://nfsa.gov.in/sso/frmPublicLogin.aspx",
    created_at: new Date().toISOString(),
  },
  {
    id: schemeIds.scheme8,
    title: "Pradhan Mantri Kaushal Vikas Yojana",
    description: "Skill development initiative for youth to enhance employability",
    category: "Skill Development",
    eligibility: "Youth aged 15-45 years seeking skill training",
    benefits: "Free short-term training courses, certification, and placement assistance",
    application_process: "Register at your nearest PMKVY Training Center or apply online",
    documents: ["Aadhaar Card", "Educational Certificates", "Bank Account Details"],
    deadline: "Ongoing with regular batches throughout the year",
    website: "https://www.india.gov.in/",
    created_at: new Date().toISOString(),
  },
  {
    id: schemeIds.scheme9,
    title: "Startup India Seed Fund Scheme",
    description: "Financial assistance for startups in early stages of development",
    category: "Entrepreneurship",
    eligibility: "DPIIT-recognized startups less than 2 years old with innovative business ideas",
    benefits: "Financial assistance up to ₹20 lakhs for proof of concept, prototype development, product trials, and market entry",
    application_process: "Apply through the Startup India portal after getting registered",
    documents: ["DPIIT Recognition Certificate", "Business Plan", "Company Registration Documents", "Bank Account Details"],
    deadline: "Rolling applications throughout the year",
    website: "https://www.startupindia.gov.in/bhaskar/register",
    created_at: new Date().toISOString(),
  },
  {
    id: schemeIds.scheme10,
    title: "Atal Pension Yojana",
    description: "Pension scheme for workers in the unorganized sector",
    category: "Finance",
    eligibility: "Citizens aged 18-40 years, primarily targeting unorganized sector workers",
    benefits: "Guaranteed minimum pension of ₹1,000 to ₹5,000 per month after the age of 60 based on contribution",
    application_process: "Apply through your bank branch or online banking",
    documents: ["Aadhaar Card", "Bank Account Details", "Mobile Number"],
    deadline: "Ongoing enrollment",
    website: "https://www.npscra.nsdl.co.in/scheme-details.php",
    created_at: new Date().toISOString(),
  },
  {
    id: schemeIds.scheme11,
    title: "PM Fasal Bima Yojana",
    description: "Crop insurance scheme to protect farmers from crop loss or damage",
    category: "Agriculture",
    eligibility: "All farmers including sharecroppers and tenant farmers growing notified crops",
    benefits: "Comprehensive insurance coverage against crop loss due to natural calamities from pre-sowing to post-harvest",
    application_process: "Enroll through banks while taking agricultural loans or directly through insurance companies",
    documents: ["Land Records", "Aadhaar Card", "Bank Account Details", "Sowing Certificate"],
    deadline: "Varies by crop season and region",
    website: "https://pmfby.gov.in/",
    created_at: new Date().toISOString(),
  },
  {
    id: schemeIds.scheme12,
    title: "National Digital Health Mission",
    description: "Digital health infrastructure for integrated healthcare delivery",
    category: "Health",
    eligibility: "All Indian citizens",
    benefits: "Health ID for every citizen, DigiDoctor, Health Facility Registry, Personal Health Records, and Telemedicine",
    application_process: "Register through the NDHM portal or mobile app",
    documents: ["Aadhaar Card", "Mobile Number"],
    deadline: "Ongoing enrollment",
    website: "https://ndhm.gov.in/",
    created_at: new Date().toISOString(),
  },
  {
    id: schemeIds.scheme13,
    title: "Sukanya Samriddhi Yojana",
    description: "Small savings scheme for the girl child",
    category: "Finance",
    eligibility: "Parents or legal guardians of a girl child below 10 years of age",
    benefits: "High interest rate (currently 7.6% compounded annually), tax benefits, and financial security for education and marriage expenses",
    application_process: "Open an account at any post office or authorized banks",
    documents: ["Girl Child's Birth Certificate", "Parent/Guardian ID Proof", "Address Proof"],
    deadline: "Can be opened until the girl child reaches 10 years of age",
    website: "https://www.indiapost.gov.in/VAS/Pages/PMODashboard/SukanyaSamriddhiAccount.aspx",
    created_at: new Date().toISOString(),
  },
  {
    id: schemeIds.scheme14,
    title: "PM-WANI (Wi-Fi Access Network Interface)",
    description: "Public Wi-Fi network to provide internet connectivity across the country",
    category: "Digital Infrastructure",
    eligibility: "All citizens in areas with PM-WANI compliant public Wi-Fi networks",
    benefits: "Free or low-cost internet access through public Wi-Fi hotspots across India",
    application_process: "Download the PM-WANI app and register with a valid ID",
    documents: ["Any Government ID", "Mobile Number"],
    deadline: "Ongoing access",
    website: "https://dot.gov.in/pm-wani",
    created_at: new Date().toISOString(),
  },
  {
    id: schemeIds.scheme15,
    title: "PM SVANidhi (Street Vendor's AtmaNirbhar Nidhi)",
    description: "Microcredit facility for street vendors affected by COVID-19",
    category: "Employment",
    eligibility: "Urban street vendors operating before March 24, 2020",
    benefits: "Working capital loan up to ₹10,000, repayable in monthly installments within 1 year, with interest subsidy on timely repayment",
    application_process: "Apply through Urban Local Bodies, Common Service Centers, or Banks",
    documents: ["Identity Card", "Certificate of Vending", "Two Photographs", "Bank Account Details"],
    deadline: "Ongoing until scheme completion",
    website: "https://pmsvanidhi.mohua.gov.in/",
    created_at: new Date().toISOString(),
  },
];

// Generate valid MongoDB ObjectIDs for FAQs
export const faqs = [
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme1,
    question: "Who is eligible for PM Kisan Samman Nidhi Yojana?",
    answer: "All landholding farmer families with cultivable land are eligible for PM Kisan. The scheme initially focused on small and marginal farmers but was later expanded to cover all farmer families regardless of land size.",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme1,
    question: "How much financial assistance is provided under PM Kisan?",
    answer: "Under PM Kisan, eligible farmer families receive ₹6,000 per year in three equal installments of ₹2,000 each, transferred directly to their bank accounts.",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme1,
    question: "How can I check my status under PM Kisan?",
    answer: "You can check your status by visiting the official PM Kisan portal (pmkisan.gov.in) and using the 'Beneficiary Status' option with your Aadhaar number, bank account number, or mobile number.",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme2,
    question: "What are the different components of Pradhan Mantri Awas Yojana?",
    answer: "PMAY has two main components: PMAY-Urban for urban areas and PMAY-Gramin for rural areas. PMAY-Urban has four verticals: in-situ slum rehabilitation, credit-linked subsidy scheme, affordable housing in partnership, and beneficiary-led individual house construction/enhancement.",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme2,
    question: "How much subsidy is provided under PMAY-Gramin?",
    answer: "Under PMAY-Gramin, beneficiaries receive financial assistance of ₹1.20 lakhs in plain areas and ₹1.30 lakhs in hilly states, difficult areas, and Integrated Action Plan districts.",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme3,
    question: "What medical services are covered under Ayushman Bharat PM-JAY?",
    answer: "PM-JAY covers most secondary and tertiary care procedures, including hospitalization, surgeries, and treatments for serious illnesses. It covers 3 days of pre-hospitalization and 15 days of post-hospitalization expenses. The scheme has over 1,350 medical packages covering treatments for cancer, neurosurgery, cardiac surgery, orthopedics, and many more.",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme3,
    question: "How do I know if I am eligible for Ayushman Bharat PM-JAY?",
    answer: "Eligibility is determined based on the Socio-Economic Caste Census (SECC) 2011 data. You can check your eligibility by visiting the PM-JAY website (pmjay.gov.in) or by calling the toll-free helpline at 14555. You can also visit your nearest Ayushman Bharat Kendra or Common Service Centre.",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme4,
    question: "What benefits are provided under Pradhan Mantri Ujjwala Yojana?",
    answer: "Under PMUY, beneficiaries receive a free LPG connection with a security deposit for one cylinder, pressure regulator, booklet, safety hose, and installation charges. Financial assistance is also provided for the first refill and stove.",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme5,
    question: "What are the different loan categories under Mudra Yojana?",
    answer: "PMMY offers three categories of loans: Shishu (loans up to ₹50,000), Kishore (loans from ₹50,000 to ₹5 lakhs), and Tarun (loans from ₹5 lakhs to ₹10 lakhs).",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme5,
    question: "Is collateral required for Mudra loans?",
    answer: "No, Mudra loans up to ₹10 lakhs are provided without collateral or third-party guarantee.",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme6,
    question: "What is the eligibility criteria for National Education Policy Scholarships?",
    answer: "Students aged 6-18 years from families with annual income below ₹2.5 lakhs, enrolled in recognized schools or colleges, and maintaining minimum attendance and academic performance are eligible.",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme8,
    question: "What types of courses are offered under PMKVY?",
    answer: "PMKVY offers short-term training in over 300 job roles across 37 sectors including automotive, healthcare, beauty & wellness, electronics, retail, logistics, construction, apparel, food processing, and more. Course duration typically ranges from 150-300 hours.",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme10,
    question: "How much do I need to contribute to get a pension of ₹5,000 per month under APY?",
    answer: "The monthly contribution amount depends on your age at enrollment and the desired pension amount. For example, if you join at age 18, you would need to contribute ₹210 per month to get a pension of ₹5,000 per month. If you join at age 40, the contribution would be ₹1,454 per month for the same pension amount.",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme11,
    question: "What is the premium rate under PM Fasal Bima Yojana?",
    answer: "Farmers pay a premium of 1.5% of the sum insured for rabi crops, 2% for kharif crops, and 5% for annual commercial and horticultural crops. The difference between the actuarial premium and the premium paid by farmers is shared equally by the Central and State Governments.",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme13,
    question: "What is the maturity period for Sukanya Samriddhi Yojana accounts?",
    answer: "The account matures after completion of 21 years from the date of opening. However, partial withdrawals up to 50% of the balance are allowed after the girl child turns 18, for higher education or marriage purposes.",
    created_at: new Date().toISOString(),
  },
]; 