export const schemes = [
  {
    id: "1",
    title: "PM Kisan Samman Nidhi Yojana",
    description: "Financial assistance to farmer families across the country",
    category: "Agriculture",
    eligibility: "All landholding farmer families with cultivable land",
    benefits: "₹6,000 per year in three equal installments",
    application_process: "Apply online through the official PM-KISAN portal or visit your nearest Common Service Centre",
    documents: ["Aadhaar Card", "Land Records", "Bank Account Details"],
    deadline: "Ongoing scheme with quarterly payments",
    website: "https://pmkisan.gov.in/",
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Pradhan Mantri Awas Yojana",
    description: "Housing for all by 2022 through financial assistance for house construction",
    category: "Housing",
    eligibility: "Households with annual income up to ₹18 lakhs, women, SC/ST, and other vulnerable groups",
    benefits: "Under PMAY-Urban, beneficiaries can receive an interest subsidy of up to ₹2.67 lakhs. Under PMAY-Gramin, financial assistance of ₹1.20 lakhs in plain areas and ₹1.30 lakhs in hilly/difficult areas is provided.",
    application_process: "Apply through the official PMAY portal or visit your local municipal office",
    documents: ["Aadhaar Card", "Income Certificate", "Property Documents", "Bank Account Details"],
    deadline: "Ongoing",
    website: "https://pmaymis.gov.in/",
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Pradhan Mantri Jan Dhan Yojana",
    description: "Financial inclusion program to ensure access to financial services",
    category: "Finance",
    eligibility: "All Indian citizens without a bank account",
    benefits: "Zero balance bank account, RuPay debit card, accidental insurance cover of ₹2 lakhs, and overdraft facility up to ₹10,000",
    application_process: "Visit any bank branch or banking correspondent with required documents",
    documents: ["Aadhaar Card", "Mobile Number", "Passport size photograph"],
    deadline: "Ongoing",
    website: "https://pmjdy.gov.in/",
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Pradhan Mantri Ujjwala Yojana",
    description: "Provision of LPG connections to women from Below Poverty Line households",
    category: "Energy",
    eligibility: "Adult women belonging to BPL households who do not have LPG connection",
    benefits: "Free LPG connection with financial assistance of ₹1,600 per connection",
    application_process: "Submit application form to nearest LPG distributor with required documents",
    documents: ["Aadhaar Card", "BPL Ration Card", "Bank Account Details"],
    deadline: "Ongoing",
    website: "https://pmuy.gov.in/",
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    title: "Pradhan Mantri Fasal Bima Yojana",
    description: "Crop insurance scheme to protect farmers from crop loss due to natural calamities",
    category: "Agriculture",
    eligibility: "All farmers including sharecroppers and tenant farmers growing notified crops",
    benefits: "Comprehensive risk coverage for pre-sowing to post-harvest losses with low premium rates",
    application_process: "Enroll through banks, insurance companies, or Common Service Centres",
    documents: ["Aadhaar Card", "Land Records", "Bank Account Details", "Crop Sowing Certificate"],
    deadline: "Varies by crop season",
    website: "https://pmfby.gov.in/",
    created_at: new Date().toISOString(),
  },
];

export const faqs = [
  {
    id: "1",
    scheme_id: "1",
    question: "Who is eligible for PM Kisan Samman Nidhi Yojana?",
    answer: "All landholding farmer families with cultivable land are eligible for this scheme. However, certain categories like institutional landholders, farmer families with one or more members as government employees, income tax payers, etc. are excluded.",
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    scheme_id: "1",
    question: "How much financial assistance is provided under PM Kisan?",
    answer: "Under PM Kisan, eligible farmer families receive ₹6,000 per year in three equal installments of ₹2,000 each, every four months.",
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    scheme_id: "1",
    question: "How can I check my PM Kisan application status?",
    answer: "You can check your application status on the official PM Kisan portal (pmkisan.gov.in) by entering your Aadhaar number or account number in the 'Beneficiary Status' section.",
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    scheme_id: "1",
    question: "What documents are required for PM Kisan registration?",
    answer: "The required documents include Aadhaar card, land records, bank account details, and a mobile number linked to your Aadhaar.",
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    scheme_id: "1",
    question: "When are the installments released?",
    answer: "The installments are typically released in the following periods: April-July, August-November, and December-March.",
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    scheme_id: "2",
    question: "Who is eligible for Pradhan Mantri Awas Yojana?",
    answer: "Eligibility varies by component, but generally includes households with an annual income up to ₹18 lakhs, women, SC/ST, and other vulnerable groups.",
    created_at: new Date().toISOString(),
  },
  {
    id: "7",
    scheme_id: "2",
    question: "What is the subsidy amount under PMAY?",
    answer: "Under PMAY-Urban, beneficiaries can receive an interest subsidy of up to ₹2.67 lakhs. Under PMAY-Gramin, financial assistance of ₹1.20 lakhs in plain areas and ₹1.30 lakhs in hilly/difficult areas is provided.",
    created_at: new Date().toISOString(),
  },
  {
    id: "8",
    scheme_id: "3",
    question: "What are the benefits of Pradhan Mantri Jan Dhan Yojana?",
    answer: "Benefits include zero balance bank account, RuPay debit card, accidental insurance cover of ₹2 lakhs, and overdraft facility up to ₹10,000.",
    created_at: new Date().toISOString(),
  },
  {
    id: "9",
    scheme_id: "4",
    question: "How can I apply for Pradhan Mantri Ujjwala Yojana?",
    answer: "You can apply by submitting an application form to the nearest LPG distributor along with required documents such as Aadhaar Card, BPL Ration Card, and bank account details.",
    created_at: new Date().toISOString(),
  },
  {
    id: "10",
    scheme_id: "5",
    question: "What is the premium rate for Pradhan Mantri Fasal Bima Yojana?",
    answer: "For Kharif crops, farmers pay a premium of 2% of the sum insured, for Rabi crops 1.5%, and for commercial and horticultural crops 5%. The remaining premium is shared by the central and state governments.",
    created_at: new Date().toISOString(),
  },
]; 