import mongoose from 'mongoose';

// Generate valid MongoDB ObjectIDs for schemes
const schemeIds = {
  scheme1: new mongoose.Types.ObjectId().toString(),
  scheme2: new mongoose.Types.ObjectId().toString(),
  scheme3: new mongoose.Types.ObjectId().toString(),
  scheme4: new mongoose.Types.ObjectId().toString(),
  scheme5: new mongoose.Types.ObjectId().toString(),
};

export const schemes = [
  {
    id: schemeIds.scheme1,
    title: "PM Kisan Samman Nidhi Yojana",
    description: "Financial assistance to farmer families across the country",
    category: "Agriculture",
    eligibility: "All landholding farmer families with cultivable land",
    benefits: "₹6,000 per year in three equal installments",
    application_process: "Apply online through the official PM-KISAN portal or visit your nearest Common Service Centre",
    documents: ["Aadhaar Card", "Land Records", "Bank Account Details"],
    deadline: "Ongoing scheme with quarterly payments",
    website: "https://pmkisan.gov.in/",
    created_at: new Date().toISOString(),
  },
  {
    id: schemeIds.scheme2,
    title: "Pradhan Mantri Awas Yojana",
    description: "Housing for all by 2022 through financial assistance for house construction",
    category: "Housing",
    eligibility: "Households with annual income up to ₹18 lakhs, women, SC/ST, and other vulnerable groups",
    benefits: "Under PMAY-Urban, beneficiaries can receive an interest subsidy of up to ₹2.67 lakhs. Under PMAY-Gramin, financial assistance of ₹1.20 lakhs in plain areas and ₹1.30 lakhs in hilly/difficult areas is provided.",
    application_process: "Apply through the official PMAY portal or visit your local municipal office",
    documents: ["Aadhaar Card", "Income Certificate", "Property Documents", "Bank Account Details"],
    deadline: "Ongoing",
    website: "https://pmaymis.gov.in/",
    created_at: new Date().toISOString(),
  },
  {
    id: schemeIds.scheme3,
    title: "Ayushman Bharat Pradhan Mantri Jan Arogya Yojana",
    description: "Health insurance scheme providing coverage up to ₹5 lakhs per family per year",
    category: "Healthcare",
    eligibility: "Poor and vulnerable families as per SECC data",
    benefits: "Free healthcare services, including hospitalization, medicines, and diagnostics up to ₹5 lakhs per family per year",
    application_process: "Check eligibility on the official website or visit your nearest Ayushman Bharat Kendra",
    documents: ["Aadhaar Card", "Ration Card", "SECC Database Details"],
    deadline: "Ongoing",
    website: "https://pmjay.gov.in/",
    created_at: new Date().toISOString(),
  },
  {
    id: schemeIds.scheme4,
    title: "Pradhan Mantri Ujjwala Yojana",
    description: "Providing LPG connections to women from BPL households",
    category: "Energy",
    eligibility: "Women from BPL households without LPG connection",
    benefits: "Free LPG connection with financial assistance for first refill and stove",
    application_process: "Apply through your nearest LPG distributor or Common Service Centre",
    documents: ["Aadhaar Card", "BPL Certificate", "Bank Account Details"],
    deadline: "Ongoing",
    website: "https://pmuy.gov.in/",
    created_at: new Date().toISOString(),
  },
  {
    id: schemeIds.scheme5,
    title: "Pradhan Mantri Mudra Yojana",
    description: "Providing loans up to ₹10 lakhs to non-corporate, non-farm small/micro enterprises",
    category: "Finance",
    eligibility: "Small businesses, entrepreneurs, and self-employed individuals",
    benefits: "Loans up to ₹10 lakhs categorized as Shishu (up to ₹50,000), Kishore (₹50,000 to ₹5 lakhs), and Tarun (₹5 lakhs to ₹10 lakhs)",
    application_process: "Apply through any commercial bank, RRB, small finance bank, or NBFC",
    documents: ["Identity Proof", "Address Proof", "Business Plan", "Bank Account Details"],
    deadline: "Ongoing",
    website: "https://www.mudra.org.in/",
    created_at: new Date().toISOString(),
  },
];

// Generate valid MongoDB ObjectIDs for FAQs
export const faqs = [
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme1,
    question: "Who is eligible for PM Kisan Samman Nidhi Yojana?",
    answer: "All landholding farmer families with cultivable land are eligible for PM Kisan. The scheme initially focused on small and marginal farmers but was later expanded to cover all farmer families regardless of land size.",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme1,
    question: "How much financial assistance is provided under PM Kisan?",
    answer: "Under PM Kisan, eligible farmer families receive ₹6,000 per year in three equal installments of ₹2,000 each, transferred directly to their bank accounts.",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme1,
    question: "How can I check my status under PM Kisan?",
    answer: "You can check your status by visiting the official PM Kisan portal (pmkisan.gov.in) and using the 'Beneficiary Status' option with your Aadhaar number, bank account number, or mobile number.",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme2,
    question: "What are the different components of Pradhan Mantri Awas Yojana?",
    answer: "PMAY has two main components: PMAY-Urban for urban areas and PMAY-Gramin for rural areas. PMAY-Urban has four verticals: in-situ slum rehabilitation, credit-linked subsidy scheme, affordable housing in partnership, and beneficiary-led individual house construction/enhancement.",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme2,
    question: "How much subsidy is provided under PMAY-Gramin?",
    answer: "Under PMAY-Gramin, beneficiaries receive financial assistance of ₹1.20 lakhs in plain areas and ₹1.30 lakhs in hilly states, difficult areas, and Integrated Action Plan districts.",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme3,
    question: "What medical services are covered under Ayushman Bharat PM-JAY?",
    answer: "PM-JAY covers most secondary and tertiary care procedures, including hospitalization, surgeries, and treatments for serious illnesses. It covers 3 days of pre-hospitalization and 15 days of post-hospitalization expenses. The scheme has over 1,350 medical packages covering treatments for cancer, neurosurgery, cardiac surgery, orthopedics, and many more.",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme3,
    question: "How do I know if I am eligible for Ayushman Bharat PM-JAY?",
    answer: "Eligibility is determined based on the Socio-Economic Caste Census (SECC) 2011 data. You can check your eligibility by visiting the PM-JAY website (pmjay.gov.in) or by calling the toll-free helpline at 14555. You can also visit your nearest Ayushman Bharat Kendra or Common Service Centre.",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme4,
    question: "What benefits are provided under Pradhan Mantri Ujjwala Yojana?",
    answer: "Under PMUY, beneficiaries receive a free LPG connection with a security deposit for one cylinder, pressure regulator, booklet, safety hose, and installation charges. Financial assistance is also provided for the first refill and stove.",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme5,
    question: "What are the different loan categories under Mudra Yojana?",
    answer: "PMMY offers three categories of loans: Shishu (loans up to ₹50,000), Kishore (loans from ₹50,000 to ₹5 lakhs), and Tarun (loans from ₹5 lakhs to ₹10 lakhs).",
    created_at: new Date().toISOString(),
  },
  {
    id: new mongoose.Types.ObjectId().toString(),
    scheme_id: schemeIds.scheme5,
    question: "Is collateral required for Mudra loans?",
    answer: "No, Mudra loans up to ₹10 lakhs are provided without collateral or third-party guarantee.",
    created_at: new Date().toISOString(),
  },
]; 